# Any Doubts Call Me!!

# Store all data into MongoDB

In [2]:
import pymongo
import json
import pandas

myclient = pymongo.MongoClient("mongodb://localhost:27017/")
mydb = myclient["Shop"]
mycol = mydb["Pawn"]

with open(r'./data.json') as f: #Enter your data.json file path
    data = json.load(f)
len(data["main"])
for each in data["main"]:
    mycol.insert_one(each)

# Connect to MongoDB

In [3]:
import pymongo

myclient = pymongo.MongoClient("mongodb://localhost:27017/")
mydb = myclient["Shop"]
mycol = mydb["Pawn"]

# Add Details to Database

In [11]:
Number = str(input("Number : "))
Amount = int(input("Amount : "))
Name = str(input("Name : "))
Relation = str(input("S/O W/O D/O : "))
Location = str(input("Location : "))
Place = str(input("Place : "))
Item_type = str(input("Item type : "))
Item = str(input("Item : "))
Pledged = str(input("Pledged Date : "))
Weight = int(input("Weight : "))

mydict={
    "Number" :Number ,
    "Amount" :Amount,
    "Name" :Name,
    "S/O W/O D/O" : Relation ,
    "Location" : Location ,
    "Place" :Place ,
    "Item" : Item,
    "Pledged Date" :Pledged,
    "Weight" : Weight
}

mycol.insert_one(mydict)

Number : AAKK 638
Amount : 5000
Name : Vasanthi
S/O W/O D/O : Mani
Location : Tiruvallue
Place : Kakalur
Item type : G
Item : Rign
Pledged Date : 15.08.2020
Weight : 19


## Fetch Stored data

In [4]:
Name = str(input("Enter name to filter : ")).title()

if Name == "":

    Number = str(input("Enter number to filter : "))
    c = mycol.find({"Number": Number})
    for d in c:
        print(d["Name"])

a = mycol.find({"Name": Name})

for b in a:
    print(b)

Enter name to filter : Haridass
{'_id': ObjectId('5f4cea7fd78c1d47fa032640'), 'Number': 'AAJ 417', 'Amount': '1900', 'Name': 'Haridass', 'S/O W/O D/O': 'Chandran', 'Location': 'Nagattaman Koil Street', 'Place': 'Erayamangalam', 'Item': 'S', 'Pledged Date': '06.02.16', 'Weight': '86'}
{'_id': ObjectId('5f4cea7fd78c1d47fa032641'), 'Number': 'AAJ 727', 'Amount': '900', 'Name': 'Haridass', 'S/O W/O D/O': 'Chandran', 'Location': 'Nagattaman Koil Street', 'Place': 'Erayamangalam', 'Item': 'G', 'Pledged Date': '28.03.16', 'Weight': '0.6'}
{'_id': ObjectId('5f4cea7fd78c1d47fa032642'), 'Number': 'AAJ 923', 'Amount': '5000', 'Name': 'Haridass', 'S/O W/O D/O': 'Chandran', 'Location': 'Nagattaman Koil Street', 'Place': 'Erayamangalam', 'Item': 'S', 'Pledged Date': '14.05.16', 'Weight': '210'}
{'_id': ObjectId('5f4cea7fd78c1d47fa032643'), 'Number': 'AAJ 924', 'Amount': '1500', 'Name': 'Haridass', 'S/O W/O D/O': 'Chandran', 'Location': 'Nagattaman Koil Street', 'Place': 'Erayamangalam', 'Item': 'G',

## Total Interset till current date by the name of person all surrender jewel

In [15]:
#The interest is calculated by 2% for each month of 30days

In [5]:
import datetime

Name = input("Enter Name : ").title()
a = mycol.find({"Name": Name})

for i in a:
    
    rates=0
    
    if i['Item'] == "G":
        rates=0.03
    else:
        rates=0.02
    
    date = i["Pledged Date"]
    amount = int(i["Amount"])
    interest=amount*rates
    final = date.replace('.','')
    date_str = final
    format_str = '%d%m%y' # The format
    datetime_obj = datetime.datetime.strptime(date_str, format_str).date()
    # print(datetime_obj)
    
    curent=datetime.datetime.now().date()

    surrendered = curent - datetime_obj

    check= surrendered.days/30

    print("₹",i['Amount'], "--" ,"₹",int(check*interest), "--" , i['Item'], "--" , i['Weight'] )

Enter Name : Haridass
₹ 1900 -- ₹ 2112 -- S -- 86
₹ 900 -- ₹ 1455 -- G -- 0.6
₹ 5000 -- ₹ 5233 -- S -- 210
₹ 1500 -- ₹ 2355 -- G -- 0.75


## OpenCV to capture image from webcam and store it into localstorage

In [13]:
# # Python Program To Read And Save image  
# import numpy as np 
# import cv2 
  
# # This will give error if you don't have a cv2 module 
# img = cv2.imread(r"C:\Users\ELCOT\Pictures\Background Screen Elcot P-VII.jpg", -1) 
  
# # img is object of cv2 and stores the image read demo.jpg 
# cv2.imwrite("outputimage.jpg", img) 
  
# # The image is saved in folder where program is stored 
# cv2.waitKey(0) 
  
# # cv2.destroyAllWindow() 

In [19]:
import cv2 

key = cv2. waitKey(1)
webcam = cv2.VideoCapture(0)
while True:
    try:
        check, frame = webcam.read()
        print(check) #prints true as long as the webcam is running
        print(frame) #prints matrix values of each framecd 
        cv2.imshow("Capturing", frame)
        key = cv2.waitKey(1)
        if key == ord('s'): 
            cv2.imwrite(filename='saved_img.jpg', img=frame)
            webcam.release()
            img_new = cv2.imread('saved_img.jpg', cv2.IMREAD_GRAYSCALE)
            img_new = cv2.imshow("Captured Image", img_new)
            cv2.waitKey(1650)
            cv2.destroyAllWindows()
            print("Processing image...")
            img_ = cv2.imread('saved_img.jpg', cv2.IMREAD_ANYCOLOR)
            print("Converting RGB image to grayscale...")
            gray = cv2.cvtColor(img_, cv2.COLOR_BGR2GRAY)
            print("Converted RGB image to grayscale...")
            print("Resizing image to 28x28 scale...")
            img_ = cv2.resize(gray,(280,280))
            print("Resized...")
            img_resized = cv2.imwrite(filename='Person1.jpg', img=img_)
            print("Image saved!")
        
            break
        elif key == ord('q'):
            print("Turning off camera.")
            webcam.release()
            print("Camera off.")
            print("Program ended.")
            cv2.destroyAllWindows()
            break
        
    except(KeyboardInterrupt):
        print("Turning off camera.")
        webcam.release()
        print("Camera off.")
        print("Program ended.")
        cv2.destroyAllWindows()
        break

True
[[[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 [[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 [[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 ...

 [[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 [[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 [[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]]
True
[[[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 [[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 [[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 ...

 [[145 143 143]
  [145 143 143]
  [145 143

True
[[[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 [[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 [[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 ...

 [[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 [[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 [[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]]
True
[[[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 [[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 [[145 143 143]
  [145 143 143]
  [145 143 143]
  ...
  [145 143 143]
  [145 143 143]
  [145 143 143]]

 ...

 [[145 143 143]
  [145 143 143]
  [145 143

In [20]:
# Imports PIL module 
from PIL import Image 

# open method used to open different extension image file 
im = Image.open(r"./Person1.jpg") 

# This method will show image in any image viewer 
im.show() 

In [10]:
# G - 2%
# S - 3%
# Every365 days
# +0.5%

In [12]:
# Nose Pin
# Besar
# Ear ring
# Tupps and Tupps
# Chimiki
# Mattal
# Nickless
# Aaram
# Chain
# Braclet
# Ring
# Anklet
# Mangalyam Items